//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniversityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UniversityName {
            get {
                return this.UniversityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UniversityNameField, value) != true)) {
                    this.UniversityNameField = value;
                    this.RaisePropertyChanged("UniversityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ClassName {
            get {
                return this.ClassNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassNameField, value) != true)) {
                    this.ClassNameField = value;
                    this.RaisePropertyChanged("ClassName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Class", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Class : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClassName {
            get {
                return this.ClassNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassNameField, value) != true)) {
                    this.ClassNameField = value;
                    this.RaisePropertyChanged("ClassName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="University", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class University : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Client.ServiceReference1.HelloWorldResponse HelloWorld(Client.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Client.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FtoC", ReplyAction="*")]
        int FtoC(int f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FtoC", ReplyAction="*")]
        System.Threading.Tasks.Task<int> FtoCAsync(int f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CtoF", ReplyAction="*")]
        int CtoF(int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CtoF", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CtoFAsync(int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDate", ReplyAction="*")]
        System.DateTime GetDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> GetDateAsync();
        
        // CODEGEN: Generating message contract since element name GetRandomResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRandom", ReplyAction="*")]
        Client.ServiceReference1.GetRandomResponse GetRandom(Client.ServiceReference1.GetRandomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRandom", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetRandomResponse> GetRandomAsync(Client.ServiceReference1.GetRandomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RonToEuro", ReplyAction="*")]
        float RonToEuro(float ron);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RonToEuro", ReplyAction="*")]
        System.Threading.Tasks.Task<float> RonToEuroAsync(float ron);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStudent", ReplyAction="*")]
        Client.ServiceReference1.AddStudentResponse AddStudent(Client.ServiceReference1.AddStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.AddStudentResponse> AddStudentAsync(Client.ServiceReference1.AddStudentRequest request);
        
        // CODEGEN: Generating message contract since element name GetStudentsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudents", ReplyAction="*")]
        Client.ServiceReference1.GetStudentsResponse GetStudents(Client.ServiceReference1.GetStudentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudents", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetStudentsResponse> GetStudentsAsync(Client.ServiceReference1.GetStudentsRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStudent", ReplyAction="*")]
        Client.ServiceReference1.UpdateStudentResponse UpdateStudent(Client.ServiceReference1.UpdateStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.UpdateStudentResponse> UpdateStudentAsync(Client.ServiceReference1.UpdateStudentRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteStudentResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteStudent", ReplyAction="*")]
        Client.ServiceReference1.DeleteStudentResponse DeleteStudent(Client.ServiceReference1.DeleteStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.DeleteStudentResponse> DeleteStudentAsync(Client.ServiceReference1.DeleteStudentRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTeacher", ReplyAction="*")]
        Client.ServiceReference1.AddTeacherResponse AddTeacher(Client.ServiceReference1.AddTeacherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTeacher", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.AddTeacherResponse> AddTeacherAsync(Client.ServiceReference1.AddTeacherRequest request);
        
        // CODEGEN: Generating message contract since element name GetTeachersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTeachers", ReplyAction="*")]
        Client.ServiceReference1.GetTeachersResponse GetTeachers(Client.ServiceReference1.GetTeachersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTeachers", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetTeachersResponse> GetTeachersAsync(Client.ServiceReference1.GetTeachersRequest request);
        
        // CODEGEN: Generating message contract since element name AddClassResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddClass", ReplyAction="*")]
        Client.ServiceReference1.AddClassResponse AddClass(Client.ServiceReference1.AddClassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddClass", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.AddClassResponse> AddClassAsync(Client.ServiceReference1.AddClassRequest request);
        
        // CODEGEN: Generating message contract since element name GetClassesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClasses", ReplyAction="*")]
        Client.ServiceReference1.GetClassesResponse GetClasses(Client.ServiceReference1.GetClassesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClasses", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetClassesResponse> GetClassesAsync(Client.ServiceReference1.GetClassesRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUniversity", ReplyAction="*")]
        Client.ServiceReference1.AddUniversityResponse AddUniversity(Client.ServiceReference1.AddUniversityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUniversity", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.AddUniversityResponse> AddUniversityAsync(Client.ServiceReference1.AddUniversityRequest request);
        
        // CODEGEN: Generating message contract since element name GetUniversitiesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUniversities", ReplyAction="*")]
        Client.ServiceReference1.GetUniversitiesResponse GetUniversities(Client.ServiceReference1.GetUniversitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUniversities", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetUniversitiesResponse> GetUniversitiesAsync(Client.ServiceReference1.GetUniversitiesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Client.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Client.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRandomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRandom", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetRandomRequestBody Body;
        
        public GetRandomRequest() {
        }
        
        public GetRandomRequest(Client.ServiceReference1.GetRandomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRandomRequestBody {
        
        public GetRandomRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRandomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRandomResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetRandomResponseBody Body;
        
        public GetRandomResponse() {
        }
        
        public GetRandomResponse(Client.ServiceReference1.GetRandomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRandomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference1.ArrayOfInt GetRandomResult;
        
        public GetRandomResponseBody() {
        }
        
        public GetRandomResponseBody(Client.ServiceReference1.ArrayOfInt GetRandomResult) {
            this.GetRandomResult = GetRandomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddStudent", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.AddStudentRequestBody Body;
        
        public AddStudentRequest() {
        }
        
        public AddStudentRequest(Client.ServiceReference1.AddStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int uId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int cId;
        
        public AddStudentRequestBody() {
        }
        
        public AddStudentRequestBody(int id, string name, string surname, int uId, int cId) {
            this.id = id;
            this.name = name;
            this.surname = surname;
            this.uId = uId;
            this.cId = cId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.AddStudentResponseBody Body;
        
        public AddStudentResponse() {
        }
        
        public AddStudentResponse(Client.ServiceReference1.AddStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddStudentResult;
        
        public AddStudentResponseBody() {
        }
        
        public AddStudentResponseBody(string AddStudentResult) {
            this.AddStudentResult = AddStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudents", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetStudentsRequestBody Body;
        
        public GetStudentsRequest() {
        }
        
        public GetStudentsRequest(Client.ServiceReference1.GetStudentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStudentsRequestBody {
        
        public GetStudentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetStudentsResponseBody Body;
        
        public GetStudentsResponse() {
        }
        
        public GetStudentsResponse(Client.ServiceReference1.GetStudentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference1.Student[] GetStudentsResult;
        
        public GetStudentsResponseBody() {
        }
        
        public GetStudentsResponseBody(Client.ServiceReference1.Student[] GetStudentsResult) {
            this.GetStudentsResult = GetStudentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStudent", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.UpdateStudentRequestBody Body;
        
        public UpdateStudentRequest() {
        }
        
        public UpdateStudentRequest(Client.ServiceReference1.UpdateStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int uId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int cId;
        
        public UpdateStudentRequestBody() {
        }
        
        public UpdateStudentRequestBody(int id, string name, string surname, int uId, int cId) {
            this.id = id;
            this.name = name;
            this.surname = surname;
            this.uId = uId;
            this.cId = cId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.UpdateStudentResponseBody Body;
        
        public UpdateStudentResponse() {
        }
        
        public UpdateStudentResponse(Client.ServiceReference1.UpdateStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateStudentResult;
        
        public UpdateStudentResponseBody() {
        }
        
        public UpdateStudentResponseBody(string UpdateStudentResult) {
            this.UpdateStudentResult = UpdateStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteStudent", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.DeleteStudentRequestBody Body;
        
        public DeleteStudentRequest() {
        }
        
        public DeleteStudentRequest(Client.ServiceReference1.DeleteStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public DeleteStudentRequestBody() {
        }
        
        public DeleteStudentRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.DeleteStudentResponseBody Body;
        
        public DeleteStudentResponse() {
        }
        
        public DeleteStudentResponse(Client.ServiceReference1.DeleteStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteStudentResult;
        
        public DeleteStudentResponseBody() {
        }
        
        public DeleteStudentResponseBody(string DeleteStudentResult) {
            this.DeleteStudentResult = DeleteStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTeacherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTeacher", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.AddTeacherRequestBody Body;
        
        public AddTeacherRequest() {
        }
        
        public AddTeacherRequest(Client.ServiceReference1.AddTeacherRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTeacherRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int uId;
        
        public AddTeacherRequestBody() {
        }
        
        public AddTeacherRequestBody(int id, string name, string surname, int uId) {
            this.id = id;
            this.name = name;
            this.surname = surname;
            this.uId = uId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTeacherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTeacherResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.AddTeacherResponseBody Body;
        
        public AddTeacherResponse() {
        }
        
        public AddTeacherResponse(Client.ServiceReference1.AddTeacherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTeacherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddTeacherResult;
        
        public AddTeacherResponseBody() {
        }
        
        public AddTeacherResponseBody(string AddTeacherResult) {
            this.AddTeacherResult = AddTeacherResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTeachersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTeachers", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetTeachersRequestBody Body;
        
        public GetTeachersRequest() {
        }
        
        public GetTeachersRequest(Client.ServiceReference1.GetTeachersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTeachersRequestBody {
        
        public GetTeachersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTeachersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTeachersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetTeachersResponseBody Body;
        
        public GetTeachersResponse() {
        }
        
        public GetTeachersResponse(Client.ServiceReference1.GetTeachersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTeachersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTeachersResult;
        
        public GetTeachersResponseBody() {
        }
        
        public GetTeachersResponseBody(string GetTeachersResult) {
            this.GetTeachersResult = GetTeachersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddClassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddClass", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.AddClassRequestBody Body;
        
        public AddClassRequest() {
        }
        
        public AddClassRequest(Client.ServiceReference1.AddClassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddClassRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int uId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int sId;
        
        public AddClassRequestBody() {
        }
        
        public AddClassRequestBody(int id, int uId, int sId) {
            this.id = id;
            this.uId = uId;
            this.sId = sId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddClassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddClassResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.AddClassResponseBody Body;
        
        public AddClassResponse() {
        }
        
        public AddClassResponse(Client.ServiceReference1.AddClassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddClassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddClassResult;
        
        public AddClassResponseBody() {
        }
        
        public AddClassResponseBody(string AddClassResult) {
            this.AddClassResult = AddClassResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClassesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClasses", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetClassesRequestBody Body;
        
        public GetClassesRequest() {
        }
        
        public GetClassesRequest(Client.ServiceReference1.GetClassesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetClassesRequestBody {
        
        public GetClassesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClassesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClassesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetClassesResponseBody Body;
        
        public GetClassesResponse() {
        }
        
        public GetClassesResponse(Client.ServiceReference1.GetClassesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetClassesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference1.Class[] GetClassesResult;
        
        public GetClassesResponseBody() {
        }
        
        public GetClassesResponseBody(Client.ServiceReference1.Class[] GetClassesResult) {
            this.GetClassesResult = GetClassesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUniversityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUniversity", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.AddUniversityRequestBody Body;
        
        public AddUniversityRequest() {
        }
        
        public AddUniversityRequest(Client.ServiceReference1.AddUniversityRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUniversityRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> sId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> tId;
        
        public AddUniversityRequestBody() {
        }
        
        public AddUniversityRequestBody(int id, string name, System.Nullable<int> sId, System.Nullable<int> tId) {
            this.id = id;
            this.name = name;
            this.sId = sId;
            this.tId = tId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUniversityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUniversityResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.AddUniversityResponseBody Body;
        
        public AddUniversityResponse() {
        }
        
        public AddUniversityResponse(Client.ServiceReference1.AddUniversityResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUniversityResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddUniversityResult;
        
        public AddUniversityResponseBody() {
        }
        
        public AddUniversityResponseBody(string AddUniversityResult) {
            this.AddUniversityResult = AddUniversityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUniversitiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUniversities", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetUniversitiesRequestBody Body;
        
        public GetUniversitiesRequest() {
        }
        
        public GetUniversitiesRequest(Client.ServiceReference1.GetUniversitiesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUniversitiesRequestBody {
        
        public GetUniversitiesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUniversitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUniversitiesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetUniversitiesResponseBody Body;
        
        public GetUniversitiesResponse() {
        }
        
        public GetUniversitiesResponse(Client.ServiceReference1.GetUniversitiesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUniversitiesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference1.University[] GetUniversitiesResult;
        
        public GetUniversitiesResponseBody() {
        }
        
        public GetUniversitiesResponseBody(Client.ServiceReference1.University[] GetUniversitiesResult) {
            this.GetUniversitiesResult = GetUniversitiesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Client.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Client.ServiceReference1.WebService1Soap>, Client.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.HelloWorldResponse Client.ServiceReference1.WebService1Soap.HelloWorld(Client.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Client.ServiceReference1.HelloWorldRequest inValue = new Client.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Client.ServiceReference1.HelloWorldRequestBody();
            Client.ServiceReference1.HelloWorldResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.HelloWorldResponse> Client.ServiceReference1.WebService1Soap.HelloWorldAsync(Client.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Client.ServiceReference1.HelloWorldRequest inValue = new Client.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Client.ServiceReference1.HelloWorldRequestBody();
            return ((Client.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
        
        public int FtoC(int f) {
            return base.Channel.FtoC(f);
        }
        
        public System.Threading.Tasks.Task<int> FtoCAsync(int f) {
            return base.Channel.FtoCAsync(f);
        }
        
        public int CtoF(int c) {
            return base.Channel.CtoF(c);
        }
        
        public System.Threading.Tasks.Task<int> CtoFAsync(int c) {
            return base.Channel.CtoFAsync(c);
        }
        
        public System.DateTime GetDate() {
            return base.Channel.GetDate();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetDateAsync() {
            return base.Channel.GetDateAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.GetRandomResponse Client.ServiceReference1.WebService1Soap.GetRandom(Client.ServiceReference1.GetRandomRequest request) {
            return base.Channel.GetRandom(request);
        }
        
        public Client.ServiceReference1.ArrayOfInt GetRandom() {
            Client.ServiceReference1.GetRandomRequest inValue = new Client.ServiceReference1.GetRandomRequest();
            inValue.Body = new Client.ServiceReference1.GetRandomRequestBody();
            Client.ServiceReference1.GetRandomResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).GetRandom(inValue);
            return retVal.Body.GetRandomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetRandomResponse> Client.ServiceReference1.WebService1Soap.GetRandomAsync(Client.ServiceReference1.GetRandomRequest request) {
            return base.Channel.GetRandomAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.GetRandomResponse> GetRandomAsync() {
            Client.ServiceReference1.GetRandomRequest inValue = new Client.ServiceReference1.GetRandomRequest();
            inValue.Body = new Client.ServiceReference1.GetRandomRequestBody();
            return ((Client.ServiceReference1.WebService1Soap)(this)).GetRandomAsync(inValue);
        }
        
        public float RonToEuro(float ron) {
            return base.Channel.RonToEuro(ron);
        }
        
        public System.Threading.Tasks.Task<float> RonToEuroAsync(float ron) {
            return base.Channel.RonToEuroAsync(ron);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.AddStudentResponse Client.ServiceReference1.WebService1Soap.AddStudent(Client.ServiceReference1.AddStudentRequest request) {
            return base.Channel.AddStudent(request);
        }
        
        public string AddStudent(int id, string name, string surname, int uId, int cId) {
            Client.ServiceReference1.AddStudentRequest inValue = new Client.ServiceReference1.AddStudentRequest();
            inValue.Body = new Client.ServiceReference1.AddStudentRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.uId = uId;
            inValue.Body.cId = cId;
            Client.ServiceReference1.AddStudentResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).AddStudent(inValue);
            return retVal.Body.AddStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.AddStudentResponse> Client.ServiceReference1.WebService1Soap.AddStudentAsync(Client.ServiceReference1.AddStudentRequest request) {
            return base.Channel.AddStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.AddStudentResponse> AddStudentAsync(int id, string name, string surname, int uId, int cId) {
            Client.ServiceReference1.AddStudentRequest inValue = new Client.ServiceReference1.AddStudentRequest();
            inValue.Body = new Client.ServiceReference1.AddStudentRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.uId = uId;
            inValue.Body.cId = cId;
            return ((Client.ServiceReference1.WebService1Soap)(this)).AddStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.GetStudentsResponse Client.ServiceReference1.WebService1Soap.GetStudents(Client.ServiceReference1.GetStudentsRequest request) {
            return base.Channel.GetStudents(request);
        }
        
        public Client.ServiceReference1.Student[] GetStudents() {
            Client.ServiceReference1.GetStudentsRequest inValue = new Client.ServiceReference1.GetStudentsRequest();
            inValue.Body = new Client.ServiceReference1.GetStudentsRequestBody();
            Client.ServiceReference1.GetStudentsResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).GetStudents(inValue);
            return retVal.Body.GetStudentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetStudentsResponse> Client.ServiceReference1.WebService1Soap.GetStudentsAsync(Client.ServiceReference1.GetStudentsRequest request) {
            return base.Channel.GetStudentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.GetStudentsResponse> GetStudentsAsync() {
            Client.ServiceReference1.GetStudentsRequest inValue = new Client.ServiceReference1.GetStudentsRequest();
            inValue.Body = new Client.ServiceReference1.GetStudentsRequestBody();
            return ((Client.ServiceReference1.WebService1Soap)(this)).GetStudentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.UpdateStudentResponse Client.ServiceReference1.WebService1Soap.UpdateStudent(Client.ServiceReference1.UpdateStudentRequest request) {
            return base.Channel.UpdateStudent(request);
        }
        
        public string UpdateStudent(int id, string name, string surname, int uId, int cId) {
            Client.ServiceReference1.UpdateStudentRequest inValue = new Client.ServiceReference1.UpdateStudentRequest();
            inValue.Body = new Client.ServiceReference1.UpdateStudentRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.uId = uId;
            inValue.Body.cId = cId;
            Client.ServiceReference1.UpdateStudentResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).UpdateStudent(inValue);
            return retVal.Body.UpdateStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.UpdateStudentResponse> Client.ServiceReference1.WebService1Soap.UpdateStudentAsync(Client.ServiceReference1.UpdateStudentRequest request) {
            return base.Channel.UpdateStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.UpdateStudentResponse> UpdateStudentAsync(int id, string name, string surname, int uId, int cId) {
            Client.ServiceReference1.UpdateStudentRequest inValue = new Client.ServiceReference1.UpdateStudentRequest();
            inValue.Body = new Client.ServiceReference1.UpdateStudentRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.uId = uId;
            inValue.Body.cId = cId;
            return ((Client.ServiceReference1.WebService1Soap)(this)).UpdateStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.DeleteStudentResponse Client.ServiceReference1.WebService1Soap.DeleteStudent(Client.ServiceReference1.DeleteStudentRequest request) {
            return base.Channel.DeleteStudent(request);
        }
        
        public string DeleteStudent(int id) {
            Client.ServiceReference1.DeleteStudentRequest inValue = new Client.ServiceReference1.DeleteStudentRequest();
            inValue.Body = new Client.ServiceReference1.DeleteStudentRequestBody();
            inValue.Body.id = id;
            Client.ServiceReference1.DeleteStudentResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).DeleteStudent(inValue);
            return retVal.Body.DeleteStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.DeleteStudentResponse> Client.ServiceReference1.WebService1Soap.DeleteStudentAsync(Client.ServiceReference1.DeleteStudentRequest request) {
            return base.Channel.DeleteStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.DeleteStudentResponse> DeleteStudentAsync(int id) {
            Client.ServiceReference1.DeleteStudentRequest inValue = new Client.ServiceReference1.DeleteStudentRequest();
            inValue.Body = new Client.ServiceReference1.DeleteStudentRequestBody();
            inValue.Body.id = id;
            return ((Client.ServiceReference1.WebService1Soap)(this)).DeleteStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.AddTeacherResponse Client.ServiceReference1.WebService1Soap.AddTeacher(Client.ServiceReference1.AddTeacherRequest request) {
            return base.Channel.AddTeacher(request);
        }
        
        public string AddTeacher(int id, string name, string surname, int uId) {
            Client.ServiceReference1.AddTeacherRequest inValue = new Client.ServiceReference1.AddTeacherRequest();
            inValue.Body = new Client.ServiceReference1.AddTeacherRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.uId = uId;
            Client.ServiceReference1.AddTeacherResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).AddTeacher(inValue);
            return retVal.Body.AddTeacherResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.AddTeacherResponse> Client.ServiceReference1.WebService1Soap.AddTeacherAsync(Client.ServiceReference1.AddTeacherRequest request) {
            return base.Channel.AddTeacherAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.AddTeacherResponse> AddTeacherAsync(int id, string name, string surname, int uId) {
            Client.ServiceReference1.AddTeacherRequest inValue = new Client.ServiceReference1.AddTeacherRequest();
            inValue.Body = new Client.ServiceReference1.AddTeacherRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.uId = uId;
            return ((Client.ServiceReference1.WebService1Soap)(this)).AddTeacherAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.GetTeachersResponse Client.ServiceReference1.WebService1Soap.GetTeachers(Client.ServiceReference1.GetTeachersRequest request) {
            return base.Channel.GetTeachers(request);
        }
        
        public string GetTeachers() {
            Client.ServiceReference1.GetTeachersRequest inValue = new Client.ServiceReference1.GetTeachersRequest();
            inValue.Body = new Client.ServiceReference1.GetTeachersRequestBody();
            Client.ServiceReference1.GetTeachersResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).GetTeachers(inValue);
            return retVal.Body.GetTeachersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetTeachersResponse> Client.ServiceReference1.WebService1Soap.GetTeachersAsync(Client.ServiceReference1.GetTeachersRequest request) {
            return base.Channel.GetTeachersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.GetTeachersResponse> GetTeachersAsync() {
            Client.ServiceReference1.GetTeachersRequest inValue = new Client.ServiceReference1.GetTeachersRequest();
            inValue.Body = new Client.ServiceReference1.GetTeachersRequestBody();
            return ((Client.ServiceReference1.WebService1Soap)(this)).GetTeachersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.AddClassResponse Client.ServiceReference1.WebService1Soap.AddClass(Client.ServiceReference1.AddClassRequest request) {
            return base.Channel.AddClass(request);
        }
        
        public string AddClass(int id, int uId, int sId) {
            Client.ServiceReference1.AddClassRequest inValue = new Client.ServiceReference1.AddClassRequest();
            inValue.Body = new Client.ServiceReference1.AddClassRequestBody();
            inValue.Body.id = id;
            inValue.Body.uId = uId;
            inValue.Body.sId = sId;
            Client.ServiceReference1.AddClassResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).AddClass(inValue);
            return retVal.Body.AddClassResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.AddClassResponse> Client.ServiceReference1.WebService1Soap.AddClassAsync(Client.ServiceReference1.AddClassRequest request) {
            return base.Channel.AddClassAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.AddClassResponse> AddClassAsync(int id, int uId, int sId) {
            Client.ServiceReference1.AddClassRequest inValue = new Client.ServiceReference1.AddClassRequest();
            inValue.Body = new Client.ServiceReference1.AddClassRequestBody();
            inValue.Body.id = id;
            inValue.Body.uId = uId;
            inValue.Body.sId = sId;
            return ((Client.ServiceReference1.WebService1Soap)(this)).AddClassAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.GetClassesResponse Client.ServiceReference1.WebService1Soap.GetClasses(Client.ServiceReference1.GetClassesRequest request) {
            return base.Channel.GetClasses(request);
        }
        
        public Client.ServiceReference1.Class[] GetClasses() {
            Client.ServiceReference1.GetClassesRequest inValue = new Client.ServiceReference1.GetClassesRequest();
            inValue.Body = new Client.ServiceReference1.GetClassesRequestBody();
            Client.ServiceReference1.GetClassesResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).GetClasses(inValue);
            return retVal.Body.GetClassesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetClassesResponse> Client.ServiceReference1.WebService1Soap.GetClassesAsync(Client.ServiceReference1.GetClassesRequest request) {
            return base.Channel.GetClassesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.GetClassesResponse> GetClassesAsync() {
            Client.ServiceReference1.GetClassesRequest inValue = new Client.ServiceReference1.GetClassesRequest();
            inValue.Body = new Client.ServiceReference1.GetClassesRequestBody();
            return ((Client.ServiceReference1.WebService1Soap)(this)).GetClassesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.AddUniversityResponse Client.ServiceReference1.WebService1Soap.AddUniversity(Client.ServiceReference1.AddUniversityRequest request) {
            return base.Channel.AddUniversity(request);
        }
        
        public string AddUniversity(int id, string name, System.Nullable<int> sId, System.Nullable<int> tId) {
            Client.ServiceReference1.AddUniversityRequest inValue = new Client.ServiceReference1.AddUniversityRequest();
            inValue.Body = new Client.ServiceReference1.AddUniversityRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.sId = sId;
            inValue.Body.tId = tId;
            Client.ServiceReference1.AddUniversityResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).AddUniversity(inValue);
            return retVal.Body.AddUniversityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.AddUniversityResponse> Client.ServiceReference1.WebService1Soap.AddUniversityAsync(Client.ServiceReference1.AddUniversityRequest request) {
            return base.Channel.AddUniversityAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.AddUniversityResponse> AddUniversityAsync(int id, string name, System.Nullable<int> sId, System.Nullable<int> tId) {
            Client.ServiceReference1.AddUniversityRequest inValue = new Client.ServiceReference1.AddUniversityRequest();
            inValue.Body = new Client.ServiceReference1.AddUniversityRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.sId = sId;
            inValue.Body.tId = tId;
            return ((Client.ServiceReference1.WebService1Soap)(this)).AddUniversityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.GetUniversitiesResponse Client.ServiceReference1.WebService1Soap.GetUniversities(Client.ServiceReference1.GetUniversitiesRequest request) {
            return base.Channel.GetUniversities(request);
        }
        
        public Client.ServiceReference1.University[] GetUniversities() {
            Client.ServiceReference1.GetUniversitiesRequest inValue = new Client.ServiceReference1.GetUniversitiesRequest();
            inValue.Body = new Client.ServiceReference1.GetUniversitiesRequestBody();
            Client.ServiceReference1.GetUniversitiesResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).GetUniversities(inValue);
            return retVal.Body.GetUniversitiesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetUniversitiesResponse> Client.ServiceReference1.WebService1Soap.GetUniversitiesAsync(Client.ServiceReference1.GetUniversitiesRequest request) {
            return base.Channel.GetUniversitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.GetUniversitiesResponse> GetUniversitiesAsync() {
            Client.ServiceReference1.GetUniversitiesRequest inValue = new Client.ServiceReference1.GetUniversitiesRequest();
            inValue.Body = new Client.ServiceReference1.GetUniversitiesRequestBody();
            return ((Client.ServiceReference1.WebService1Soap)(this)).GetUniversitiesAsync(inValue);
        }
    }
}
